### ISSUE TITLE
Little problem with definition of   'i'

### ISSUE THREAD

**Issue by galvanetto** [project-ida/two-state-quantum-systems#18]
https://github.com/project-ida/two-state-quantum-systems/blob/master/03-a-two-state-system-in-a-quantised-field.ipynb

`omegas = np.ones(i+1)*2*A`

Gives me `NameError: name 'i' is not defined`

@mklilley I think you can fix it on the fly, Maybe you already had `i` stored on memory when you run it

**Comment by mklilley** [comment]
Thanks @galvanetto - I missed that one.
 I've made a little PR that fixes it
