### ISSUE TITLE
02-perturbing... inaccurate description of the 2 wells analogy

### ISSUE THREAD

**Issue by galvanetto** [project-ida/two-state-quantum-systems#9]
Not a problem in the code, but 
"We can understand 2 by recalling that the perturbation creates an energy difference between the |+> and |->. We can think of the perturbation as a barrier between the two states - the larger the barrier the less effective the coupling between the states will be and the more likely you'll stay in the state you started in."

I think it is not correct: the perturbation is not the width of the barrier (that is the coupling) but the difference of the height of the two wells. With zero perturbation you have two wells at the same (vertical) level. If you introduce the delta, you move one up, the other down.

**Comment by mklilley** [comment]
Hi Nicola.

I agree, the perturbation is the height of the barrier (which also enters into the [tunnelling probability](http://hyperphysics.phy-astr.gsu.edu/hbase/quantum/barr.html)). Perhaps I could make it clearer by saying 

> We can think of the perturbation as a barrier between the two states - the larger the **perturbation the higher** the barrier **and so** the less effective the coupling between the states will be and the more likely you'll stay in the state you started in

What do you think?

**Comment by galvanetto** [comment]
No again it is wrong in my opinion. 
The coupling **A** is related to the height and the width of the Barrier;
The **deta** is related to the different height of the bottom of the wells, that of course depends also on the height of the barrier, but we can assume that the delta is small compare to that.

![image](https://user-images.githubusercontent.com/28784964/75443032-e3b14700-5960-11ea-83ba-fe6aeac207c6.png)

**Comment by mklilley** [comment]
Yes, I see what you mean. Let me think on it and read the article you shared. Perhaps I'll find a better mental picture.

**Comment by galvanetto** [comment]
I updated text in master
